spring.application.name=sistema-avisos
server.port=8082

spring.datasource.url=jdbc:h2:mem:sistema_avisos
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=a8f7c2d9e1b4a6c3f9d0e7a2c5a1f8e8e6c9b3a7e0f2c8d1a2b1e6f3c7d4a2b8
security.subsystem.base-url=http://localhost:8080
security.subsystem.system-key=PALA_SYS_35E4A4A89AA0361F4811240BA7AB3EF3
