spring.application.name=sistema-avisos
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=${JWT_SECRET:a8f7c2d9e1b4a6c3f9d0e7a2c5a1f8e8e6c9b3a7e0f2c8d1a2b1e6f3c7d4a2b8}
security.subsystem.base-url=${SECURITY_SUBSYSTEM_BASE_URL:https://subsistemaseguridadpala.onrender.com}
security.subsystem.system-key=${SECURITY_SUBSYSTEM_SYSTEM_KEY:PALA_SYS_35E4A4A89AA0361F4811240BA7AB3EF3}
security.subsystem.jwt.secret=${SECURITY_SUBSYSTEM_JWT_SECRET:${JWT_SECRET:a8f7c2d9e1b4a6c3f9d0e7a2c5a1f8e8e6c9b3a7e0f2c8d1a2b1e6f3c7d4a2b8}}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://sistema-p-a-l-afront.vercel.app}
