package com.facultad.sistemaavisos.conexioncarrera;
import com.facultad.sistemaavisos.carrera.*; import com.facultad.sistemaavisos.shared.exception.*;
import lombok.RequiredArgsConstructor; import org.jsoup.Jsoup; import org.jsoup.nodes.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.net.*; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class ConexionCarreraService {
 private final ConexionCarreraRepository conexiones; private final CarreraRepository carreras;
 public List<ConexionCarrera> listar(){return conexiones.findAll();}
 public ConexionCarrera crear(String nombre,String url){validarUrl(url); return conexiones.save(ConexionCarrera.builder().nombreConexionCarrera(nombre.trim()).urlConexionCarrera(url.trim()).fechaCreacionConexionCarrera(Instant.now()).build());}
 public ConexionCarrera actualizar(Long id,String nombre,String url){validarUrl(url);var c=buscar(id);c.setNombreConexionCarrera(nombre.trim());c.setUrlConexionCarrera(url.trim());return conexiones.save(c);}
 public ConexionCarrera baja(Long id){var c=buscar(id);c.setFechaBajaConexionCarrera(Instant.now());return conexiones.save(c);}
 public ConexionCarrera reactivar(Long id){var c=buscar(id);c.setFechaBajaConexionCarrera(null);return conexiones.save(c);}
 public long cantidad(Long id){return carreras.countByConexionCarrera_Id(id);}
 private ConexionCarrera buscar(Long id){return conexiones.findById(id).orElseThrow(()->new RecursoNoEncontradoException("Conexion no encontrada"));}
 public Resultado sincronizar(Long id,boolean confirmar){var c=conexiones.findById(id).orElseThrow(()->new RecursoNoEncontradoException("Conexion no encontrada")); if(c.getFechaBajaConexionCarrera()!=null)throw new OperacionInvalidaException("La conexion esta dada de baja"); var encontrados=scrapear(c.getUrlConexionCarrera()); var actuales=carreras.findByConexionCarrera_Id(id); var claves=encontrados.stream().map(Item::clave).collect(java.util.stream.Collectors.toSet()); int nuevos=0,actualizados=0,bajas=0; for(var i:encontrados){var ex=carreras.findByConexionCarrera_IdAndClaveExternaCarrera(id,i.clave()).orElse(null); if(ex==null)nuevos++; else if(!ex.getNombreCarrera().equals(i.nombre())||ex.getFechaBajaCarrera()!=null)actualizados++; if(confirmar){if(ex==null) ex=Carrera.builder().conexionCarrera(c).claveExternaCarrera(i.clave()).fechaAltaCarrera(Instant.now()).build(); ex.setNombreCarrera(i.nombre());ex.setDescripcionCarrera(i.descripcion());ex.setUrlOrigenCarrera(i.url());ex.setFechaActualizacionCarrera(Instant.now());ex.setFechaBajaCarrera(null);carreras.save(ex);}}
 for(var ex:actuales)if(!claves.contains(ex.getClaveExternaCarrera())&&ex.getFechaBajaCarrera()==null){bajas++;if(confirmar){ex.setFechaBajaCarrera(Instant.now());carreras.save(ex);}}
 if(confirmar){c.setFechaUltimaSincronizacion(Instant.now());conexiones.save(c);} return new Resultado(encontrados.size(),nuevos,actualizados,bajas,encontrados);}
 private List<Item> scrapear(String url){try{Document d=Jsoup.connect(url).userAgent("PALA-Academic-Sync/1.0").timeout(10000).maxBodySize(2_000_000).get();Map<String,Item> out=new LinkedHashMap<>();for(Element h:d.select("h2")){String t=h.text().trim();if(t.isBlank()||t.toLowerCase().contains("leer")||Set.of("Ingenierías","Tecnicaturas","Licenciaturas","Información","Contactos","Visitas").contains(t))continue;Element card=h.closest(".elementor-widget-wrap");if(card==null)continue;Element a=card.selectFirst("h2 a[href]");if(a==null||!a.text().toLowerCase().contains("leer"))continue;Element p=card.selectFirst("p");String desc=p==null?"":p.text().trim();String link=a.absUrl("href");String nombre=(desc.length()<140&&(desc.startsWith("Tecnicatura")||desc.startsWith("Licenciatura")))?desc:t;String clave=!link.isBlank()?link.toLowerCase():nombre.toLowerCase();out.putIfAbsent(clave,new Item(clave,nombre,desc,link));}if(out.isEmpty())throw new OperacionInvalidaException("No se detectaron carreras; revise la URL o el formato del sitio");return new ArrayList<>(out.values());}catch(java.io.IOException e){throw new OperacionInvalidaException("No se pudo consultar la URL: "+e.getMessage());}}
 private void validarUrl(String value){try{URI u=URI.create(value);String h=u.getHost();if(!"https".equals(u.getScheme())||h==null||!(h.equals("frm.utn.edu.ar")||h.equals("www4.frm.utn.edu.ar")))throw new Exception();}catch(Exception e){throw new OperacionInvalidaException("Solo se permiten URLs HTTPS oficiales de frm.utn.edu.ar");}}
 public record Item(String clave,String nombre,String descripcion,String url){} public record Resultado(int detectadas,int nuevas,int actualizadas,int dadasDeBaja,List<Item> carreras){}
}
